[project]
name = "esphome_powermonitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "esptool>=5.1.0",
    "tornado>=6.5.4",
]
